#!/usr/bin/env bash

[ -z $SMTP_DOMAIN ] && SMTP_DOMAIN=localhost

cat <<EOF > /etc/ssmtp/ssmtp.conf
mailhub=${SMTP_RELAYHOST}
hostname=${SMTP_DOMAIN}
rewriteDomain=${SMTP_DOMAIN}
UseTLS=Yes
UseSTARTTLS=Yes
AuthUser=${SMTP_USER}
AuthPass=${SMTP_PASS}
FROMLineOverride=yes
EOF

